---
- hosts: test
  tasks:
  - name: Installing Latest version of Apache
    yum: pkg=httpd state=latest
  - name: Upload Copying the demo file
    copy: src=/var/www/html/ram dest=/var/www/html
              owner=apache group=apache mode=0644
  - name: (Enable it on System Boot)
    service: name=httpd enabled=yes
    notify:
    - start apache
  handlers:
    - name: start apache
      service: name=httpd state=started
